#%RAML 1.0 Trait
usage: Standard error response structure

responses:
  204:
    description: 
      The request succeeded
  400:
    description: Bad Request
    body:
      application/json:
        example:
          type: !include ../datatypes/errorDataType.raml
          message: "Bad Request"
  404:
    description: 404 NOT FOUND
    body: 
      application/json:
        example:
          type: !include ../datatypes/errorDataType.raml
          message: "Not Found."
  500:
    description: Internal Server Error
    body:
      application/json:
        example:
          type: !include ../datatypes/errorDataType.raml
          message: "Internal Server Error"      